apiVersion: apps/v1
kind: Deployment
metadata:
  name: anonymoususer-frontend-deployment
  namespace: anonymoususer-rls
spec:
  selector:
    matchLabels:
      app: embedded-anonymous-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: embedded-anonymous-frontend
    spec:
      containers:
      - name: embedded-anonymousfrontend
        image: us-docker.pkg.dev/boldbi-294612/embed-application/boldbi-anonymous-frontend:testfrontend

        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 750Mi
        volumeMounts:
        - name: nginx-config-volume
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config-volume
        configMap:
          name: nginx-config