# Generated by Django 3.2.8 on 2021-10-21 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboardapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiResponse',
        ),
    ]
